version: '3.3'

services:
  imc_calc:
    image: imc_calc
    container_name: imc_calc
    build: .
    entrypoint: python3 app.py
    ports:
      - 5000:5000
    restart: on-failure
    networks:
      mec-apps:
        aliases:
          - imc_calc

networks:
  mec-apps:
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24