---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imc_app
  namespace: mec-apps
  labels:
    app.kubernetes.io/name: imc_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imc_app
  template:
    metadata:
      labels:
        app: imc_app
    spec:
      containers:
        - name: imc_app
          imagePullPolicy: Never
          image: imc_app:1.0
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: imc_app-svc
  namespace: mec-apps
spec:
  ports:
    - port: 5000      
  selector:
    app: imc_app
  type: ClusterIP
