---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mts_api
  namespace: default
  labels:
    app.kubernetes.io/name: mts_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mts_api
  template:
    metadata:
      labels:
        app: mts_api
    spec:
      containers:
        - name: mts_api
          imagePullPolicy: Never
          image: mts_api:1.0
          ports:
          - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: mts_api
  namespace: default
spec:
  ports:
  - nodePort: 32005
    port: 6000
    targetPort: 6000
  selector:
    app: mts_api
  type: NodePort
