---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mts-api
  namespace: default
  labels:
    app.kubernetes.io/name: mts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mts-api
  template:
    metadata:
      labels:
        app: mts-api
    spec:
      containers:
        - name: mts-api
          imagePullPolicy: Never
          image: mts-api:1.0
          ports:
          - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: mts-api-svc
  namespace: default
spec:
  ports:
  - nodePort: 32005
    port: 6000
    targetPort: 6000
  selector:
    app: mts-api
  type: NodePort
