info:
  version: 1.0.0
  description: UPF configuration

configuration:
  # debugLevel: panic|fatal|error|warn|info|debug|trace
  debugLevel: info

  pfcp:
    - addr: upfMec.free5gc.org

  gtpu:
    - addr: upfMec.free5gc.org
    # [optional] gtpu.name
    # - name: upf.5gc.nctu.me
    # [optional] gtpu.ifname
    # - ifname: gtpif

  dnn_list:
    - dnn: internet #MEC
      cidr: 60.61.0.0/16
     #natifname: eth1
      # [optional] apn_list[*].natifname
      # natifname: eth0
